{% set version = "3.5.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: 1c22877758cef97e81dbb665c83d31f7427bbc804a01503fa2845a35403c54ad

build:
  number: 0
  skip: true  # [py<36]
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python
    - jupyter >=1.0.0,<2.0.0
    - pandas >=1.0.0,<2.0.0

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter widget for Vega 5 and Vega-Lite 4

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
